### ISSUE TITLE
Use go modules

### ISSUE THREAD

**Issue by soypat** [Gabo-Tor/gocellular#2]
Use go modules so users can run the program and track `go.mod` file for reproducible builds.

Steps:
1. Initialize the module running `go mod init gocellular` in the base directory. This generates an empty `go.mod` file with the name of the module "gocellular".
2. run `go mod tidy`. The go tool will then fetch dependencies for the project and update the `go.mod` file. The tool will also generate the `go.sum` file, which provides the project with exact versions for all required modules ensuring reproducible builds with these two files. This file is not "required" but helps ensure consistent builds.

The result is that now anyone who clones the application with the `go.mod` file can run the application from scratch. Take that virtual environments.

**Comment by Gabo-Tor** [comment]
Done
